[logger]
# Level of logging: "error", "warning", "info", or "debug"
level = "info"

# String format for logging messages
messageFormat = "%(asctime)s - %(levelname)s - %(message)s"

[global]
# Remove the invalid showErrorDetails option
# Only include valid options like:
disableWidgetStateDuplicationWarning = false
showWarningOnDirectExecution = true